state_names_long_to_short = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}
state_names_short_to_long = {v: k for k, v in state_names_long_to_short.items()}
ec_vote_size = {
    'AK': 3,
    'AL': 9,
    'AR': 6,
    'AZ': 11,
    'CA': 55,
    'CO': 9,
    'CT': 7,
    'DC': 3,
    'DE': 3,
    'FL': 29,
    'GA': 16,
    'HI': 4,
    'IA': 6,
    'ID': 4,
    'IL': 20,
    'IN': 11,
    'KS': 6,
    'KY': 8,
    'LA': 8,
    'MA': 11,
    'MD': 10,
    'ME': 4,
    'MI': 16,
    'MN': 10,
    'MO': 10,
    'MS': 6,
    'MT': 3,
    'NC': 15,
    'ND': 3,
    'NE': 5,
    'NH': 4,
    'NJ': 14,
    'NM': 5,
    'NV': 6,
    'NY': 29,
    'OH': 18,
    'OK': 7,
    'OR': 7,
    'PA': 20,
    'RI': 4,
    'SC': 9,
    'SD': 3,
    'TN': 11,
    'TX': 38,
    'UT': 6,
    'VA': 13,
    'VT': 3,
    'WA': 12,
    'WI': 10,
    'WV': 5,
    'WY': 3
}
states = list(state_names_short_to_long.keys())
